"use client";
import { useLocale } from "next-intl";
import { useEffect, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata based on locale
const metadata = {
  en: {
    title: "Internationalized Web Page",
    description: "Generated by create next app",
  },
  id: {
    title: "Halaman Web Internasional",
    description: "Dihasilkan oleh create next app dalam bahasa Indonesia",
  },
};

export default function RootLayout({ children }) {
  const locale = useLocale();
  const [currentMetadata, setCurrentMetadata] = useState(metadata.en);

  useEffect(() => {
    setCurrentMetadata(metadata[locale] || metadata.en);
  }, [locale]);

  return (
    <html lang={locale}>
      <head>
        <title>{currentMetadata.title}</title>
        <meta name="description" content={currentMetadata.description} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}
      >
        <Header />
        <main className="container mx-auto px-4 py-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
